name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  build:
    if: |
      !(github.event.pull_request.draft == true &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'ci:skip'))
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ChargeUnity/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Pre-fetch dependencies
        run: mvn dependency:go-offline

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            ChargeUnity/backend/target/classes
            ChargeUnity/backend/target/*.jar

  test:
    if: |
      !(github.event.pull_request.draft == true &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'ci:skip'))
    name: Test and Coverage
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ChargeUnity/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ChargeUnity/backend/target/

      - name: Run tests and generate coverage
        run: mvn test jacoco:report -T 4

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ChargeUnity/backend/target/site/jacoco/

  sonar:
    if: |
      !(github.event.pull_request.draft == true &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'ci:skip'))
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ChargeUnity/backend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ChargeUnity/backend/target/

      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: ChargeUnity/backend/target/site/jacoco/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ChargeUnity/backend
          args: >
            -Dsonar.projectKey=ChargeUnity_TQS_ChargeUnity
            -Dsonar.organization=chargeunity
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  integration-test:
    if: |
      !(github.event.pull_request.draft == true &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'ci:skip'))
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ChargeUnity/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ChargeUnity/backend/target/

      - name: Run integration tests
        run: ./mvnw test -Dtest=*IT