name: Enforce Coding Styling

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:

  format:
    if: |
      !(github.event.pull_request.draft == true &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'ci:skip'))
    name: Format Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Google Java Format
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--skip-sorting-imports --replace"
          skip-commit: true

      - name: Show git diff
        run: git --no-pager diff

      - name: Commit and push needed changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Apply Google Java Format"
            git push origin HEAD:$branch_name
          else
            echo "No formatting changes to commit."
          fi