name: CD - Deploy ChargeUnity (teste na CH-88)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: ChargeUnity Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Parar containers anteriores
        working-directory: ChargeUnity
        run: docker compose --env-file .env -f docker-compose.yml down

      - name: Limpar cache de imagens antigas
        run: docker builder prune -a -f

      - name: Build backend (Maven)
        run: mvn -f ChargeUnity/backend/pom.xml clean package

      - name: Subir serviços com Docker Compose
        working-directory: ChargeUnity
        run: docker compose --env-file .env -f docker-compose.yml up -d --build

      
