name: CD - Deploy ChargeUnity (teste na CH-88)

on:
  push:
    branches:
      - CH-88-Create-draft-CD-pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: ChargeUnity Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar ficheiro .env com secrets
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_PORT=3307:3306" >> .env
          echo "APP_PORT=8080:8080" >> .env
          echo "FRONTEND_PORT_VITE=5173:5173" >> .env
          echo "VITE_APP_API_URL=http://localhost:8080" >> .env
          echo "DB_EMAIL=${{ secrets.DB_EMAIL }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Verificar diretório atual (debug)
        run: pwd && ls -l

      - name: Parar containers anteriores
        run: docker compose --env-file .env -f ChargeUnity/docker-compose.yml down

      - name: Limpar cache de imagens antigas
        run: docker builder prune -a -f

      - name: Subir serviços com Docker Compose
        run: docker compose --env-file .env -f ChargeUnity/docker-compose.yml up -d --build

      - name: Verificar healthcheck do backend
        run: curl --fail http://localhost:8080/actuator/health

      - name: Verificar healthcheck do frontend
        run: curl --fail http://localhost:5173
