on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze'
        default: 'main'

jobs:
  sonarcloud_manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ChargeUnity/backend
          args: >
            -Dsonar.projectKey=ChargeUnity_TQS_ChargeUnity
            -Dsonar.organization=chargeunity
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
